project_id = "qromvrzqktrfexbnaoem"

[functions.login]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.validate-session]
verify_jwt = false

[functions.get-monitoring-data]
verify_jwt = false

[functions.get-users]
verify_jwt = false
